name: Test Changes
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Get Rust
        id: rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt, llvm-tools
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Install grcov
        uses: actions-rs/install@v0.1
        with:
          crate: grcov
          version: latest

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run clippy
        uses: actions-rs/cargo@v1.0.3
        with:
          command: clippy
          args: --all-targets --all-features

      - name: Run fmt check
        uses: actions-rs/cargo@v1.0.3
        with:
          command: fmt
          args: --check --all

      - name: Run tests
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
          args: --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-Cinstrument-coverage -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off"

      - name: Collect code coverage
        id: coverage
        uses: actions-rs/grcov@v0.1

      - name: Upload code coverage
        uses: codecov/codecov-action@v1.2.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./lcov.info
