name: Test Changes
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Get Rust
        id: rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: Check out code
        uses: actions/checkout@v4

      - name: Run clippy
        uses: actions-rs/cargo@v1.0.3
        with:
          command: clippy
          args: --all-targets --all-features

      - name: Run fmt check
        uses: actions-rs/cargo@v1.0.3
        with:
          command: fmt
          args: --check --all

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.15.0'
          args: '-- --test-threads 1'

      - name: Upload code coverage
        uses: codecov/codecov-action@v5.1.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
